// <auto-generated />
using System;
using System.Collections.Generic;
using BookRight.InfrastructureLib.Persistance.DbContextFiles;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookRight.InfrastructureLib.Migrations
{
    [DbContext(typeof(BookRightDbContext))]
    [Migration("20260528063558_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookRight.DomainLib.Entities.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiscountTypeUsed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParticipantLimit")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TherapistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TreatmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_participants")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Participants");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Time", "BookRight.DomainLib.Entities.Bookings.Booking.Time#TimeSlot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("From");

                            b1.Property<DateTime>("To");

                            b1
                                .ToJson("Time")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BookRight.DomainLib.Entities.Campaigns.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedTreatments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AssignedTreatments");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CampaignPeriod", "BookRight.DomainLib.Entities.Campaigns.Campaign.CampaignPeriod#CampaignPeriod", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("From");

                            b1.Property<DateOnly>("To");

                            b1
                                .ToJson("CampaignPeriod")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("BookRight.DomainLib.Entities.Clinics.Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TreatmentRoomLimit")
                        .HasColumnType("int");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "BookRight.DomainLib.Entities.Clinics.Clinic.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired();

                            b1.Property<string>("PostalCode")
                                .IsRequired();

                            b1.Property<string>("Street")
                                .IsRequired();

                            b1
                                .ToJson("Address")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("BookRight.DomainLib.Entities.Clinics.OpeningHour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly?>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<TimeOnly?>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<string>("WeekDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("OpeningHours");
                });

            modelBuilder.Entity("BookRight.DomainLib.Entities.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PreferredTherapistId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "BookRight.DomainLib.Entities.Customers.Customer.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired();

                            b1.Property<string>("PostalCode")
                                .IsRequired();

                            b1.Property<string>("Street")
                                .IsRequired();

                            b1
                                .ToJson("Address")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "BookRight.DomainLib.Entities.Customers.Customer.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("EmailAddress")
                                .IsRequired();

                            b1
                                .ToJson("Email")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PhoneNumber", "BookRight.DomainLib.Entities.Customers.Customer.PhoneNumber#PhoneNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Number")
                                .IsRequired();

                            b1
                                .ToJson("PhoneNumber")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BookRight.DomainLib.Entities.Therapists.Therapist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorizationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_associatedClinics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AssociatedClinics");

                    b.Property<string>("_certificationTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CertificationTypes");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "BookRight.DomainLib.Entities.Therapists.Therapist.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired();

                            b1.Property<string>("PostalCode")
                                .IsRequired();

                            b1.Property<string>("Street")
                                .IsRequired();

                            b1
                                .ToJson("Address")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "BookRight.DomainLib.Entities.Therapists.Therapist.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("EmailAddress")
                                .IsRequired();

                            b1
                                .ToJson("Email")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PhoneNumber", "BookRight.DomainLib.Entities.Therapists.Therapist.PhoneNumber#PhoneNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Number")
                                .IsRequired();

                            b1
                                .ToJson("PhoneNumber")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Therapists");
                });

            modelBuilder.Entity("BookRight.DomainLib.Entities.Treatments.Treatment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CertificationRequired")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Treatments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("68a14b26-15d6-4831-a876-221b01260c6b"),
                            CertificationRequired = "Acupuncture",
                            Duration = new TimeSpan(0, 0, 45, 0, 0),
                            MaxParticipants = 1,
                            Name = "Acupuncture 45",
                            Price = 550m
                        },
                        new
                        {
                            Id = new Guid("f748fc78-c660-4de0-a1a8-f7c0b0930f98"),
                            CertificationRequired = "Dietary",
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            MaxParticipants = 1,
                            Name = "Dietary Guidance follow-up",
                            Price = 450m
                        },
                        new
                        {
                            Id = new Guid("79b16d43-7475-4409-bd12-ddd0e2067863"),
                            CertificationRequired = "Dietary",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            MaxParticipants = 1,
                            Name = "Dietary Guidance first time",
                            Price = 799m
                        },
                        new
                        {
                            Id = new Guid("2f1196bb-8d78-444c-bcdb-992806905c6e"),
                            CertificationRequired = "Physiotherapy",
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            MaxParticipants = 1,
                            Name = "Physiotherapy 30",
                            Price = 395m
                        },
                        new
                        {
                            Id = new Guid("53bb0fec-b7ee-45c7-ae0e-0db7f508658d"),
                            CertificationRequired = "Physiotherapy",
                            Duration = new TimeSpan(0, 0, 45, 0, 0),
                            MaxParticipants = 1,
                            Name = "Physiotherapy 45",
                            Price = 589m
                        },
                        new
                        {
                            Id = new Guid("4ced2638-f883-42fa-ad82-24902b3b1ba4"),
                            CertificationRequired = "Physiotherapy",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            MaxParticipants = 1,
                            Name = "Physiotherapy 60",
                            Price = 745m
                        },
                        new
                        {
                            Id = new Guid("b83d128e-f408-40f8-b4ad-25c31250cf2b"),
                            CertificationRequired = "Massage",
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            MaxParticipants = 1,
                            Name = "Sports Massage 30",
                            Price = 350m
                        },
                        new
                        {
                            Id = new Guid("710cfebd-245c-410d-b63f-9e066f77de39"),
                            CertificationRequired = "Massage",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            MaxParticipants = 1,
                            Name = "Sports Massage 60",
                            Price = 699m
                        },
                        new
                        {
                            Id = new Guid("4401a516-76ba-497f-beba-aee749850ddd"),
                            CertificationRequired = "Rehabilitation",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            MaxParticipants = 6,
                            Name = "Team Training Rehabilitation",
                            Price = 150m
                        });
                });

            modelBuilder.Entity("BookRight.DomainLib.Entities.Clinics.OpeningHour", b =>
                {
                    b.HasOne("BookRight.DomainLib.Entities.Clinics.Clinic", null)
                        .WithMany("OpeningHours")
                        .HasForeignKey("ClinicId");
                });

            modelBuilder.Entity("BookRight.DomainLib.Entities.Clinics.Clinic", b =>
                {
                    b.Navigation("OpeningHours");
                });
#pragma warning restore 612, 618
        }
    }
}
